SELECT DISTINCT D.ID,
                D.EMAIL,
                D.FIRST_NAME,
                D.LAST_NAME
FROM DEVELOPERS D
LEFT OUTER JOIN SKILLCODES S
ON (D.SKILL_CODE % (S.CODE * 2)) >= S.CODE
WHERE S.NAME = 'Python'OR S.NAME = 'C#'
ORDER BY D.ID;